#!/bin/bash
#SBATCH -A cc3uv3p # 2017 XSEDE Applications of Parallel Computing Course Allocation
#SBATCH -J auto-particle-mpi16
#SBATCH -o auto-particle-mpi16.stdout
#SBATCH -n 16         
#SBATCH -p RM
#SBATCH -t 00:10:00     
#SBATCH -N 1      

rm mpi_sum.txt
./serial -n 500 -no -s mpi_sum.txt
./mpi -n 500 -no -s mpi_sum.txt
./mpi -n 500 -no -s mpi_sum.txt
./mpi -n 500 -no -s mpi_sum.txt
./mpi -n 500 -no -s mpi_sum.txt
./mpi -n 500 -no -s mpi_sum.txt
./mpi -n 1000 -no -s mpi_sum.txt
./mpi -n 2000 -no -s mpi_sum.txt
./mpi -n 4000 -no -s mpi_sum.txt
./mpi -n 8000 -no -s mpi_sum.txt
./autograder -v mpi -s mpi_sum.txt
